import Footer from './components/Footer'
import Header from './components/Header'
import PageWrapper from './components/PageWrapper'
import './globals.css'
import { DM_Sans} from 'next/font/google'

const dmSans = DM_Sans({ 
  weight: ["400", "500", "700"],
  subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`dark:bg-black ${dmSans.className}`}>
        <PageWrapper>
        <Header />
        {children}
        <Footer />
        </PageWrapper>
        </body>
    </html>
  )
}
